// Histórico resumido dos 66 livros — autoria tradicional, época aproximada e
// tema central, escrito de forma geral e não-denominacional (o Ministério
// Avivar do Espírito é interdenominacional). Baseado em tradições de autoria
// amplamente aceitas e em consenso geral sobre época e tema; onde a autoria é
// incerta ou debatida entre estudiosos, isso é indicado explicitamente.
// Revise e ajuste conforme a ênfase da sua igreja antes de publicar.

export const BOOK_HISTORY = {
  // ---- Antigo Testamento ----
  gn: {
    autor: "Tradicionalmente Moisés",
    epoca: "Eventos narrados desde a criação até cerca de 1800 a.C.; redação tradicional por volta do século XV a.C.",
    tema: "As origens — criação, queda, dilúvio e os patriarcas",
    texto: "Gênesis abre as Escrituras narrando a criação do mundo, a origem da humanidade, a entrada do pecado e as primeiras alianças de Deus com o ser humano. Os capítulos 1–11 tratam de temas universais (criação, queda, dilúvio, dispersão dos povos), enquanto os capítulos 12–50 acompanham a história dos patriarcas — Abraão, Isaque, Jacó e José — mostrando como Deus vai formando um povo a partir de uma família.",
  },
  ex: {
    autor: "Tradicionalmente Moisés",
    epoca: "Êxodo do Egito por volta do século XV ou XIII a.C. (data debatida entre estudiosos)",
    tema: "Libertação do Egito e a aliança no Sinai",
    texto: "Êxodo narra a escravidão do povo hebreu no Egito, o chamado de Moisés, as dez pragas e a travessia do Mar Vermelho. A segunda metade do livro descreve a aliança firmada no Monte Sinai, a entrega dos Dez Mandamentos e as instruções para a construção do Tabernáculo, onde Deus prometeu habitar em meio ao seu povo.",
  },
  lv: {
    autor: "Tradicionalmente Moisés",
    epoca: "Período do acampamento no Sinai, logo após o Êxodo",
    tema: "Santidade, sacrifícios e leis sacerdotais",
    texto: "Levítico reúne as instruções dadas aos sacerdotes levitas sobre sacrifícios, purificação ritual, o Dia da Expiação e as leis de santidade que deveriam distinguir Israel das nações vizinhas. O tema central que atravessa o livro é o chamado repetido: 'sede santos, porque eu sou santo'.",
  },
  nm: {
    autor: "Tradicionalmente Moisés",
    epoca: "Os quarenta anos de peregrinação no deserto",
    tema: "A jornada do deserto e as consequências da desconfiança",
    texto: "Números recebe esse nome pelos dois censos do povo registrados no livro. Narra a jornada de Israel do Sinai até as fronteiras de Canaã, incluindo os episódios de murmuração, a recusa em entrar na terra prometida por falta de fé, e a consequente peregrinação de uma geração inteira pelo deserto.",
  },
  dt: {
    autor: "Tradicionalmente Moisés",
    epoca: "Últimos dias de Moisés, antes da entrada em Canaã",
    tema: "Renovação da aliança antes da conquista",
    texto: "Deuteronômio ('segunda lei') registra os discursos finais de Moisés à nova geração de Israel, relembrando a jornada do deserto e renovando a aliança do Sinai antes da entrada na terra prometida. É um dos livros mais citados por Jesus e pelos apóstolos no Novo Testamento.",
  },
  js: {
    autor: "Tradicionalmente Josué, com edições posteriores",
    epoca: "Conquista de Canaã, por volta do século XV ou XIII a.C.",
    tema: "A conquista e a divisão da terra prometida",
    texto: "Josué narra a entrada do povo de Israel em Canaã sob a liderança de Josué, sucessor de Moisés, incluindo a queda de Jericó e a divisão da terra entre as doze tribos. O livro encerra com a renovação da aliança e o célebre chamado: 'escolhei hoje a quem sirvais'.",
  },
  jz: {
    autor: "Autor incerto; tradição atribui a Samuel",
    epoca: "Período entre a conquista e o início da monarquia, cerca de séculos XIV–XI a.C.",
    tema: "Ciclos de apostasia, opressão e libertação",
    texto: "Juízes descreve um período turbulento em que Israel repetidamente se afasta de Deus, é oprimido por povos vizinhos, clama por socorro e é libertado por líderes chamados juízes — entre eles Gideão, Débora e Sansão. O refrão do livro, 'cada um fazia o que parecia certo aos seus próprios olhos', resume a desordem espiritual da época.",
  },
  rt: {
    autor: "Autor incerto",
    epoca: "Ambientado no período dos Juízes; escrito possivelmente na época de Davi",
    tema: "Fidelidade e redenção em meio à adversidade",
    texto: "Rute conta a história de uma mulher moabita que, por lealdade à sua sogra Noemi, deixa sua terra e encontra redenção através de Boaz, um parente resgatador. O livro termina revelando que Rute se torna bisavó do rei Davi, ligando essa pequena história familiar à grande narrativa de Israel.",
  },
  "1sm": {
    autor: "Autor incerto; tradição associa a Samuel e outros profetas",
    epoca: "Cerca do século XI a.C.",
    tema: "A transição dos juízes para a monarquia",
    texto: "1 Samuel narra o nascimento e ministério do profeta Samuel, a rejeitada mas concedida pedido de um rei, a ascensão e queda de Saul, e a unção de Davi como o escolhido de Deus. É um livro marcado pelo contraste entre a obediência de coração e a aparência externa de liderança.",
  },
  "2sm": {
    autor: "Autor incerto",
    epoca: "Reinado de Davi, cerca de 1010–970 a.C.",
    tema: "O reinado de Davi — triunfos e quedas",
    texto: "2 Samuel acompanha o reinado de Davi sobre Israel unido, incluindo a conquista de Jerusalém, a promessa de uma dinastia eterna (a aliança davídica) e também suas falhas graves, como o episódio com Bate-Seba, com suas consequências dentro da própria família real.",
  },
  "1rs": {
    autor: "Autor incerto",
    epoca: "De cerca de 970 a.C. até a divisão do reino",
    tema: "O apogeu de Salomão e a divisão do reino",
    texto: "1 Reis narra o reinado de Salomão, a construção do Templo de Jerusalém e o auge da prosperidade de Israel, seguido pela divisão do reino em Israel (norte) e Judá (sul) após sua morte, e o início do ciclo de reis fiéis e infiéis em ambos os reinos.",
  },
  "2rs": {
    autor: "Autor incerto",
    epoca: "Da divisão do reino até a queda de Judá, 931–586 a.C.",
    tema: "O declínio e queda dos dois reinos",
    texto: "2 Reis continua a história dos reis de Israel e Judá, incluindo os ministérios dos profetas Elias e Eliseu, até a queda do reino do Norte para a Assíria (722 a.C.) e do reino do Sul para a Babilônia (586 a.C.), encerrando com o povo levado ao exílio.",
  },
  "1cr": {
    autor: "Tradicionalmente Esdras",
    epoca: "Escrito após o exílio, cerca do século V a.C., narrando desde Adão até Davi",
    tema: "Genealogias e o reinado de Davi, sob perspectiva sacerdotal",
    texto: "1 Crônicas abre com extensas genealogias que ligam o povo pós-exílico à sua herança desde Adão, e depois narra o reinado de Davi com ênfase especial na adoração, no culto e nos preparativos para a construção do Templo — uma perspectiva voltada para restaurar a identidade espiritual de Israel após o exílio.",
  },
  "2cr": {
    autor: "Tradicionalmente Esdras",
    epoca: "Escrito após o exílio, narrando de Salomão até o edito de Ciro",
    tema: "O reinado de Salomão e dos reis de Judá, até o exílio",
    texto: "2 Crônicas percorre o reinado de Salomão e depois se concentra apenas nos reis de Judá (omitindo o reino do Norte), destacando os momentos de reforma e fidelidade ao Templo. O livro termina com o decreto do rei Ciro permitindo o retorno do povo a Jerusalém.",
  },
  ed: {
    autor: "Tradicionalmente Esdras",
    epoca: "Cerca de 538–450 a.C.",
    tema: "O retorno do exílio e a reconstrução do Templo",
    texto: "Esdras narra o retorno dos exilados judeus da Babilônia sob o decreto de Ciro, a reconstrução do Templo de Jerusalém em meio a oposição, e a chegada posterior do sacerdote e escriba Esdras, que lidera uma reforma espiritual e moral entre o povo.",
  },
  ne: {
    autor: "Tradicionalmente Neemias (memórias em primeira pessoa)",
    epoca: "Cerca de 445–430 a.C.",
    tema: "A reconstrução dos muros de Jerusalém",
    texto: "Neemias, copeiro do rei persa, obtém permissão para retornar a Jerusalém e liderar a reconstrução dos muros da cidade, apesar de forte oposição externa. O livro também registra a renovação da aliança e reformas sociais e religiosas conduzidas junto com Esdras.",
  },
  et: {
    autor: "Autor desconhecido",
    epoca: "Reinado do rei persa Xerxes (Assuero), cerca de 483–473 a.C.",
    tema: "A providência de Deus por trás dos bastidores",
    texto: "Ester conta como uma jovem judia se torna rainha da Pérsia e, com coragem, intercede para salvar seu povo de um plano de extermínio. É o único livro da Bíblia que não menciona o nome de Deus diretamente, mas sua providência é sentida em cada reviravolta da trama — origem da festa judaica de Purim.",
  },
  job: {
    autor: "Autor desconhecido",
    epoca: "Ambientação patriarcal muito antiga; data de composição incerta",
    tema: "O sofrimento humano e a soberania de Deus",
    texto: "Jó é uma obra poética profunda sobre um homem íntegro que perde tudo e enfrenta um sofrimento aparentemente sem sentido, debatendo com seus amigos sobre a causa de sua dor. O livro não oferece uma resposta simples, mas conduz Jó a um encontro pessoal com a grandeza e soberania de Deus.",
  },
  sl: {
    autor: "Múltiplos autores — Davi é o mais citado; também Asafe, os filhos de Coré, Salomão e Moisés",
    epoca: "Composição ao longo de vários séculos, do tempo de Moisés ao período pós-exílico",
    tema: "O hinário e livro de orações de Israel",
    texto: "Salmos reúne 150 poemas e cânticos usados na adoração de Israel, cobrindo toda a gama da experiência humana diante de Deus: louvor, lamento, arrependimento, confiança e ação de graças. É um dos livros mais lidos da Bíblia por dar linguagem à oração pessoal e comunitária em qualquer época.",
  },
  pv: {
    autor: "Principalmente Salomão, com contribuições de outros sábios",
    epoca: "Reinado de Salomão, cerca do século X a.C., com adições posteriores",
    tema: "Sabedoria prática para a vida cotidiana",
    texto: "Provérbios reúne ditos curtos e memoráveis sobre como viver com sabedoria — nas finanças, no trabalho, nos relacionamentos e no caráter. O princípio que organiza o livro é declarado logo no início: 'o temor do Senhor é o princípio do conhecimento'.",
  },
  ec: {
    autor: "Tradicionalmente Salomão",
    epoca: "Tradicionalmente final do reinado de Salomão, século X a.C.",
    tema: "O sentido da vida 'debaixo do sol'",
    texto: "Eclesiastes é uma reflexão honesta e às vezes desconcertante sobre a busca de sentido na riqueza, no prazer, no trabalho e no conhecimento humano, concluindo que tudo isso, vivido à parte de Deus, é 'vaidade'. O livro termina apontando para o temor a Deus e a obediência aos seus mandamentos como o verdadeiro fundamento da vida.",
  },
  ct: {
    autor: "Tradicionalmente Salomão",
    epoca: "Tradicionalmente reinado de Salomão, século X a.C.",
    tema: "O amor conjugal como dom de Deus",
    texto: "Cantares de Salomão é um poema lírico que celebra o amor e o desejo entre um casal, com linguagem poética rica em imagens da natureza. Ao longo da história foi lido tanto como celebração do amor humano quanto, alegoricamente, como imagem do amor entre Deus e seu povo.",
  },
  is: {
    autor: "Tradicionalmente o profeta Isaías (autoria única ou múltipla é debatida entre estudiosos)",
    epoca: "Cerca de 740–680 a.C.",
    tema: "Julgamento, consolo e esperança messiânica",
    texto: "Isaías é um dos maiores livros proféticos, alternando fortes advertências contra a infidelidade de Judá com algumas das promessas messiânicas mais citadas do Antigo Testamento — incluindo as passagens sobre o Servo Sofredor, amplamente associadas por cristãos a Jesus Cristo.",
  },
  jr: {
    autor: "O profeta Jeremias, com registros de seu escriba Baruque",
    epoca: "Cerca de 627–580 a.C., até pouco após a queda de Jerusalém",
    tema: "Advertência e lamento antes da queda de Jerusalém",
    texto: "Jeremias ministrou em um dos períodos mais dramáticos da história de Judá, advertindo repetidamente sobre o juízo iminente por causa da infidelidade do povo, enquanto era rejeitado e perseguido. O livro também contém a promessa de uma 'nova aliança' escrita no coração, citada no Novo Testamento.",
  },
  lm: {
    autor: "Tradicionalmente Jeremias",
    epoca: "Logo após a queda de Jerusalém, 586 a.C.",
    tema: "Lamento pela destruição de Jerusalém",
    texto: "Lamentações é uma série de cinco poemas de luto pela destruição de Jerusalém e do Templo pelos babilônios, expressando dor profunda sem deixar de reconhecer a fidelidade de Deus — é dali que vem a conhecida afirmação: 'as suas misericórdias se renovam cada manhã'.",
  },
  ez: {
    autor: "O profeta Ezequiel",
    epoca: "Cerca de 593–571 a.C., durante o exílio na Babilônia",
    tema: "Visões e esperança de restauração durante o exílio",
    texto: "Ezequiel profetizou entre os exilados na Babilônia, combinando advertências dramáticas com visões simbólicas marcantes — como o vale de ossos secos — apontando para a restauração futura de Israel e a promessa de um coração novo dado pelo Espírito de Deus.",
  },
  dn: {
    autor: "Tradicionalmente Daniel",
    epoca: "Cerca de 605–530 a.C., durante o exílio babilônico e persa",
    tema: "Fidelidade em terra estrangeira e visões apocalípticas",
    texto: "Daniel narra episódios conhecidos de fidelidade a Deus em meio a pressão pagã — a cova dos leões, a fornalha ardente — e visões proféticas sobre impérios futuros, sendo um dos textos mais citados quando se fala de profecia apocalíptica na Bíblia.",
  },
  os: {
    autor: "O profeta Oséias",
    epoca: "Cerca de 755–715 a.C.",
    tema: "A fidelidade de Deus apesar da infidelidade de Israel",
    texto: "Oséias usa sua própria experiência conjugal dolorosa como metáfora viva do relacionamento entre Deus e um Israel infiel, mostrando ao mesmo tempo o peso da traição e a profundidade do amor que não desiste.",
  },
  jl: {
    autor: "O profeta Joel",
    epoca: "Data incerta, possivelmente entre os séculos IX e V a.C.",
    tema: "O 'Dia do Senhor' e o derramamento do Espírito",
    texto: "Joel usa uma devastadora praga de gafanhotos como ponto de partida para um chamado ao arrependimento e para a promessa de que Deus derramaria seu Espírito 'sobre toda a carne' — texto citado por Pedro no dia de Pentecostes, em Atos 2.",
  },
  am: {
    autor: "O profeta Amós",
    epoca: "Cerca de 760–750 a.C.",
    tema: "Justiça social e verdadeira adoração",
    texto: "Amós, um pastor de ovelhas do sul, é enviado para denunciar a injustiça social e a religiosidade vazia no próspero reino do Norte, com o clamor conhecido: 'corra a justiça como as águas, e a retidão, como ribeiro perene'.",
  },
  ob: {
    autor: "O profeta Obadias",
    epoca: "Data incerta, possivelmente logo após a queda de Jerusalém",
    tema: "Julgamento sobre Edom",
    texto: "O menor livro do Antigo Testamento anuncia o julgamento de Deus sobre Edom, nação vizinha e parente de Israel, por seu orgulho e por se voltar contra o povo de Deus em seu momento de maior fragilidade.",
  },
  jn: {
    autor: "Tradicionalmente o profeta Jonas",
    epoca: "Cerca do século VIII a.C.",
    tema: "A misericórdia de Deus alcança até os inimigos",
    texto: "Jonas narra a fuga de um profeta que se recusa a pregar arrependimento à cidade inimiga de Nínive, sua experiência dentro do grande peixe, e a surpreendente misericórdia de Deus sobre a cidade quando ela finalmente se arrepende — evidenciando que o coração de Deus alcança além das fronteiras de Israel.",
  },
  mq: {
    autor: "O profeta Miquéias",
    epoca: "Cerca de 735–700 a.C.",
    tema: "Justiça, julgamento e esperança messiânica",
    texto: "Miquéias combina fortes denúncias contra a injustiça das lideranças de Israel com uma das definições mais conhecidas de verdadeira religião — 'praticar a justiça, amar a misericórdia e andar humildemente com o teu Deus' — além de profetizar o nascimento do Messias em Belém.",
  },
  na: {
    autor: "O profeta Naum",
    epoca: "Entre 663 e 612 a.C.",
    tema: "A queda de Nínive",
    texto: "Naum anuncia o julgamento final sobre Nínive, capital da Assíria, décadas depois do arrependimento registrado em Jonas — mostrando que a misericórdia de Deus não anula sua justiça quando a maldade persiste.",
  },
  hc: {
    autor: "O profeta Habacuque",
    epoca: "Cerca de 609–598 a.C.",
    tema: "Fé em meio à dúvida",
    texto: "Habacuque é incomum entre os profetas por registrar um diálogo direto entre o profeta e Deus, questionando por que a injustiça prospera — e chegando à célebre conclusão de fé: 'o justo viverá pela sua fé', citada três vezes no Novo Testamento.",
  },
  sf: {
    autor: "O profeta Sofonias",
    epoca: "Cerca de 640–609 a.C.",
    tema: "O Dia do Senhor e a promessa de restauração",
    texto: "Sofonias adverte sobre o julgamento iminente de Judá e das nações vizinhas, mas encerra com uma das mais belas promessas de restauração e alegria do Antigo Testamento, incluindo a imagem de Deus 'se alegrando' sobre seu povo com cânticos.",
  },
  ag: {
    autor: "O profeta Ageu",
    epoca: "520 a.C.",
    tema: "A reconstrução do Templo",
    texto: "Ageu incentiva o povo recém-retornado do exílio a retomar a reconstrução do Templo, interrompida por desânimo e prioridades pessoais, prometendo que a glória futura daquela casa seria maior que a anterior.",
  },
  zc: {
    autor: "O profeta Zacarias",
    epoca: "Cerca de 520–480 a.C.",
    tema: "Visões e esperança messiânica",
    texto: "Zacarias combina visões simbólicas incentivando a reconstrução do Templo com profecias messiânicas marcantes, incluindo a imagem do rei que viria 'mansamente montado em jumento' — citada nos evangelhos na entrada de Jesus em Jerusalém.",
  },
  ml: {
    autor: "O profeta Malaquias",
    epoca: "Cerca de 430 a.C.",
    tema: "Fidelidade no culto e a promessa de um mensageiro",
    texto: "Malaquias, o último livro do Antigo Testamento na ordem cristã, repreende a negligência espiritual e ritual do povo pós-exílico e termina anunciando a vinda de um mensageiro que prepararia o caminho do Senhor — ponte direta para os quatrocentos anos de silêncio até o Novo Testamento.",
  },

  // ---- Novo Testamento ----
  mt: {
    autor: "Tradicionalmente o apóstolo Mateus",
    epoca: "Cerca de 50–70 d.C.",
    tema: "Jesus como o Messias que cumpre as Escrituras",
    texto: "Mateus escreve principalmente para um público judeu, mostrando repetidamente como Jesus cumpre as profecias do Antigo Testamento. É organizado em cinco grandes blocos de ensino, incluindo o Sermão do Monte, e apresenta Jesus como o Rei prometido.",
  },
  mc: {
    autor: "Tradicionalmente João Marcos",
    epoca: "Cerca de 55–70 d.C., possivelmente o evangelho mais antigo",
    tema: "Jesus como o Servo que age",
    texto: "Marcos é o evangelho mais curto e direto, com ritmo acelerado ('logo' aparece dezenas de vezes) e forte ênfase nas ações de Jesus mais do que em longos discursos, apresentando-o como o Servo sofredor que 'não veio para ser servido, mas para servir'.",
  },
  lc: {
    autor: "Tradicionalmente Lucas, o médico, companheiro de Paulo",
    epoca: "Cerca de 60–80 d.C.",
    tema: "Jesus como Salvador de todos, com atenção aos marginalizados",
    texto: "Lucas escreve com cuidado histórico explícito (Lucas 1:1-4) para um público majoritariamente gentio, destacando o cuidado de Jesus com pobres, mulheres, samaritanos e pecadores — evangelho que mais contém parábolas conhecidas, como o Filho Pródigo e o Bom Samaritano.",
  },
  jo: {
    autor: "Tradicionalmente o apóstolo João",
    epoca: "Cerca de 85–95 d.C.",
    tema: "A divindade de Cristo revelada em sinais e discursos",
    texto: "Diferente dos evangelhos sinóticos, João organiza seu relato em torno de sete grandes sinais e longos discursos de Jesus, com o objetivo declarado: 'para que creiais que Jesus é o Cristo, o Filho de Deus'. É marcado por afirmações fortes sobre a divindade de Cristo desde o prólogo.",
  },
  at: {
    autor: "Tradicionalmente Lucas (continuação do seu evangelho)",
    epoca: "Cerca de 62–80 d.C., narrando eventos de 30–62 d.C.",
    tema: "A expansão da igreja primitiva pelo poder do Espírito Santo",
    texto: "Atos narra o nascimento da igreja em Jerusalém no dia de Pentecostes e sua expansão por todo o mundo mediterrâneo, acompanhando primeiro o ministério de Pedro e depois as viagens missionárias de Paulo, sempre sob a marca do poder do Espírito Santo agindo através de gente comum.",
  },
  rm: {
    autor: "O apóstolo Paulo",
    epoca: "Cerca de 57 d.C.",
    tema: "O evangelho explicado sistematicamente",
    texto: "Escrita à igreja de Roma, esta carta é considerada a exposição mais sistemática do evangelho no Novo Testamento — percorrendo a condição pecaminosa da humanidade, a justificação pela fé, a nova vida no Espírito, e encerrando com orientações práticas para a vida cristã em comunidade.",
  },
  "1co": {
    autor: "O apóstolo Paulo",
    epoca: "Cerca de 53–54 d.C.",
    tema: "Correção e unidade numa igreja dividida",
    texto: "1 Coríntios responde a uma série de problemas concretos na igreja de Corinto — divisões, imoralidade, processos judiciais entre irmãos, uso dos dons espirituais — culminando no célebre capítulo 13 sobre o amor e no capítulo 15 sobre a ressurreição.",
  },
  "2co": {
    autor: "O apóstolo Paulo",
    epoca: "Cerca de 55–56 d.C.",
    tema: "Defesa do apostolado e reconciliação",
    texto: "2 Coríntios é a carta mais pessoal de Paulo, na qual ele defende sua autoridade apostólica contra acusadores, descreve suas próprias fraquezas e sofrimentos como palco do poder de Deus, e apela pela reconciliação plena com a igreja.",
  },
  gl: {
    autor: "O apóstolo Paulo",
    epoca: "Cerca de 48–55 d.C. (data debatida)",
    tema: "Justificação pela fé, não pelas obras da lei",
    texto: "Gálatas é a defesa apaixonada de Paulo contra ensinos que exigiam obediência à lei judaica para a salvação, afirmando que a justificação vem exclusivamente pela fé em Cristo e que a vida cristã se vive 'pelo Espírito', em liberdade.",
  },
  ef: {
    autor: "O apóstolo Paulo (durante prisão)",
    epoca: "Cerca de 60–62 d.C.",
    tema: "A igreja como corpo de Cristo",
    texto: "Efésios apresenta uma visão elevada do plano eterno de Deus e da igreja como o corpo de Cristo, unindo judeus e gentios num só povo, com a segunda metade da carta dedicada a como essa nova identidade deve moldar o caráter e os relacionamentos práticos.",
  },
  fp: {
    autor: "O apóstolo Paulo (durante prisão)",
    epoca: "Cerca de 60–62 d.C.",
    tema: "Alegria e contentamento em Cristo",
    texto: "Filipenses é conhecida como 'a carta da alegria' — escrita da prisão, Paulo expressa gratidão e contentamento apesar das circunstâncias, incluindo o hino cristológico sobre a humilhação e exaltação de Cristo (capítulo 2).",
  },
  cl: {
    autor: "O apóstolo Paulo (durante prisão)",
    epoca: "Cerca de 60–62 d.C.",
    tema: "A supremacia e suficiência de Cristo",
    texto: "Colossenses combate ensinos que diminuíam a pessoa de Cristo, afirmando com força sua supremacia sobre toda a criação e toda autoridade espiritual, e que nele o crente já tem tudo o que precisa.",
  },
  "1ts": {
    autor: "O apóstolo Paulo",
    epoca: "Cerca de 50–51 d.C., uma das cartas mais antigas de Paulo",
    tema: "Esperança na volta de Cristo",
    texto: "1 Tessalonicenses encoraja uma igreja jovem em meio à perseguição, esclarecendo dúvidas sobre o que acontece com os que morrem antes da volta de Cristo e incentivando uma vida de santidade enquanto se aguarda esse dia.",
  },
  "2ts": {
    autor: "O apóstolo Paulo",
    epoca: "Cerca de 51–52 d.C.",
    tema: "Esclarecimentos sobre a volta de Cristo",
    texto: "2 Tessalonicenses corrige um mal-entendido de que o Dia do Senhor já teria chegado, descrevendo eventos que precisam ocorrer antes, e reforça o chamado ao trabalho e à perseverança enquanto se espera.",
  },
  "1tm": {
    autor: "O apóstolo Paulo",
    epoca: "Cerca de 62–64 d.C.",
    tema: "Ordem e liderança saudável na igreja",
    texto: "1 Timóteo é uma das 'cartas pastorais', com instruções práticas de Paulo ao seu discípulo Timóteo sobre organização da igreja, qualificações de líderes e como combater falsos ensinos.",
  },
  "2tm": {
    autor: "O apóstolo Paulo",
    epoca: "Cerca de 64–67 d.C., provavelmente sua última carta",
    tema: "Perseverança até o fim",
    texto: "2 Timóteo traz o tom mais pessoal e comovente entre as cartas de Paulo, escrita perto do fim de sua vida, exortando Timóteo a permanecer firme na Palavra e a 'combater o bom combate' com a mesma fidelidade que ele próprio buscou manter.",
  },
  tt: {
    autor: "O apóstolo Paulo",
    epoca: "Cerca de 62–64 d.C.",
    tema: "Liderança e boas obras em Creta",
    texto: "Tito, outra carta pastoral, instrui um jovem líder sobre como organizar a igreja em Creta e insiste que a sã doutrina deve necessariamente produzir boas obras visíveis na vida prática dos crentes.",
  },
  fm: {
    autor: "O apóstolo Paulo (durante prisão)",
    epoca: "Cerca de 60–62 d.C.",
    tema: "Apelo pessoal por reconciliação e perdão",
    texto: "Filemom é a carta mais curta e pessoal de Paulo, um apelo delicado a Filemom para que receba de volta e perdoe seu escravo fugitivo Onésimo, agora convertido — um retrato prático do evangelho aplicado a uma relação humana concreta.",
  },
  hb: {
    autor: "Autor anônimo; a tradição sugeriu vários nomes (Paulo, Barnabé, Apolo, entre outros), mas o consenso moderno é que a autoria é incerta",
    epoca: "Provavelmente antes de 70 d.C.",
    tema: "A superioridade de Cristo sobre o antigo sistema",
    texto: "Hebreus argumenta extensamente que Cristo é superior aos anjos, a Moisés e ao sacerdócio levítico, sendo o sumo sacerdote perfeito e definitivo — encorajando leitores tentados a abandonar a fé a perseverarem, 'olhando para Jesus, autor e consumador da fé'.",
  },
  tg: {
    autor: "Tradicionalmente Tiago, irmão de Jesus e líder da igreja de Jerusalém",
    epoca: "Possivelmente uma das primeiras cartas do NT, cerca de 45–50 d.C.",
    tema: "Fé genuína que se mostra em obras",
    texto: "Tiago é uma carta intensamente prática, quase no estilo de Provérbios, insistindo que a fé verdadeira necessariamente produz frutos visíveis — no controle da língua, no cuidado com os necessitados e na integridade diante das provações.",
  },
  "1pe": {
    autor: "O apóstolo Pedro",
    epoca: "Cerca de 62–64 d.C.",
    tema: "Esperança viva em meio ao sofrimento",
    texto: "1 Pedro escreve a cristãos espalhados que enfrentavam sofrimento e hostilidade, lembrando-os de sua identidade como 'povo escolhido' e apontando para o sofrimento de Cristo como exemplo e fonte de esperança em meio às provações.",
  },
  "2pe": {
    autor: "O apóstolo Pedro",
    epoca: "Cerca de 64–68 d.C.",
    tema: "Alerta contra falsos mestres",
    texto: "2 Pedro adverte contra falsos mestres que negavam a volta de Cristo e viviam de forma corrupta, incentivando os leitores a crescerem 'na graça e no conhecimento' enquanto aguardam o cumprimento das promessas de Deus.",
  },
  "1jo": {
    autor: "Tradicionalmente o apóstolo João",
    epoca: "Cerca de 85–95 d.C.",
    tema: "Certeza da fé e amor fraternal",
    texto: "1 João combate ensinos que negavam a humanidade plena de Cristo, oferecendo testes práticos para que o leitor tenha certeza de sua fé — obediência, amor ao próximo e reconhecimento de Jesus como Cristo vindo em carne.",
  },
  "2jo": {
    autor: "Tradicionalmente o apóstolo João",
    epoca: "Cerca de 85–95 d.C.",
    tema: "Verdade e amor, com alerta contra falsos mestres",
    texto: "2 João, uma carta curta, equilibra o chamado a andar no amor com a advertência de não acolher quem ensina falsas doutrinas sobre Cristo.",
  },
  "3jo": {
    autor: "Tradicionalmente o apóstolo João",
    epoca: "Cerca de 85–95 d.C.",
    tema: "Hospitalidade e liderança na igreja local",
    texto: "3 João é uma carta pessoal elogiando a hospitalidade de Gaio para com missionários itinerantes, em contraste com a atitude controladora de outro líder chamado Diótrefes.",
  },
  jd: {
    autor: "Tradicionalmente Judas, irmão de Tiago e de Jesus",
    epoca: "Cerca de 65–80 d.C.",
    tema: "Alerta contra falsos mestres e apostasia",
    texto: "Judas é uma carta curta e vigorosa alertando contra pessoas que se infiltravam nas igrejas distorcendo a graça de Deus, encerrando com uma das doxologias mais conhecidas do Novo Testamento.",
  },
  ap: {
    autor: "Tradicionalmente o apóstolo João, escrevendo do exílio em Patmos",
    epoca: "Cerca de 90–96 d.C.",
    tema: "A vitória final de Cristo sobre o mal",
    texto: "Apocalipse é uma visão profética rica em símbolos, endereçada a sete igrejas sofrendo perseguição, revelando o controle soberano de Cristo sobre a história e culminando na promessa de um novo céu e nova terra onde Deus habitará para sempre com seu povo.",
  },
};
